language: python

sudo: false

branches:
  only:
  - master
  - "/^v\\d+\\.\\d+$/"
  - "/^\\d\\.\\d+$/"
  - "/^\\d\\.\\d+\\.\\d+(rc\\d+|\\.dev\\d+)?$/"

matrix:
  include:
  - dist: xenial
    env: TOXENV=py37
    python: 3.7
  - env: TOXENV=docs
    python: 3.7
  - env: TOXENV=docs-coverage
    python: 3.7
  - env: TOXENV=docs-links
    python: 3.7

install:
- pip install -U tox twine wheel codecov

script: tox

after_success:
- codecov

cache:
  directories:
  - "$HOME/.cache/pip"
